### ISSUE TITLE
Webpack fails in chapter 05

### ISSUE THREAD

**Issue by seanknox** [PacktPublishing/Cloud-Native-programming-with-Golang#4]
Running webpack in `frontend/` returns the following error:

```
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'ts' of undefined
    at getLoaderOptions (/Users/seanknox/go/src/github.com/PacktPublishing/Cloud-Native-programming-with-Golang/Chapter05/frontend/node_modules/ts-loader/dist/index.js:70:44)
    at Object.loader (/Users/seanknox/go/src/github.com/PacktPublishing/Cloud-Native-programming-with-Golang/Chapter05/frontend/node_modules/ts-loader/dist/index.js:23:19)
```

**Comment by seanknox** [comment]
@minaandrawos @martin-helmich FYI

**Comment by mzuber88** [comment]
@seanknox I know this is a year later, but I ran into the same issue.  Basically newer webpack doesn't work with the older source from this project.  It looks like it was using webpack 2.7.0.  So I just did: 
`npm install -g webpack@2.7`

Sometimes it's confusing when you are trying to follow the book but also already have the source since the git repo has the node_modules in the checkout.  So when doing chapter 5, you only care about running the commands that npm install globally with -g and ignore all the others because they will be in in the node_modules directory of the gitrepo.
